services:
  - type: web
    name: third-party-risk-management
    env: node
    buildCommand: |
      # Install dependencies in root directory
      npm install
      # Install dependencies in subdomain-scanner directory
      cd subdomain-scanner
      npm install
      npm run build
    startCommand: cd subdomain-scanner && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: NODE_ENV
        value: production
    autoDeploy: true 